Add timeout on integration tests no canton debug (#54)
* remove canton debug logging in integraiton tests

* always upload tests results even if there are failures

* set 10min timeout per bats test

* continue executing job even if test encounters an error

* do not fail test or test reporter if tests fail, but the step afterward

* do not rely on logs to indicate sandbox started

* uptick actions versions

* fix wait for canton check

* add grpcurl

* increase bash test timeout

* add grpcurl via nix for linux/osx, add via choco for windows GHA

* install grpcurl via winget for windows

* suppress transfer progress noise for mvn compile

* include gcloud auth login

* improvement to error handling

* Revert "include gcloud auth login"

This reverts commit 8426ae6edaf51cb48fd4b473780491cf05424c11.

* minimal changes

* install grpcurl on windows

* run windows install in bash

* make sure the status is SERVING

* correct grpcurl url

* launch sandbox in coproc same way as in other places

* use windows paths

* do not fail on empty reporter

diff --git a/.github/actions/test-release/action.yml b/.github/actions/test-release/action.yml
--- a/.github/actions/test-release/action.yml
+++ b/.github/actions/test-release/action.yml
@@ -54,15 +54,28 @@ runs:
       shell: bash -euo pipefail -c "source nix.source && exec bash -euo pipefail $0" "{0}"
 
     - name: Run integration tests
+      id: run-tests
+      continue-on-error: true
+      env:
+        BATS_TEST_TIMEOUT: 300
+        VERSION: ${{ inputs.version }}
       run: |
-        VERSION=${{ inputs.version }} bats ./test/sdk-integration.bats --report-formatter junit --output "${RUNNER_TEMP}/test-output"
+        bats ./test/sdk-integration.bats --report-formatter junit --output "${RUNNER_TEMP}/test-output"
       shell: bash -euo pipefail -c "source nix.source && exec bash -euo pipefail $0" "{0}"
 
     - name: Test Report
-      uses: dorny/test-reporter@fe45e9537387dac839af0d33ba56eed8e24189e8 # v2.3.0
+      uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2 # v3.0.0
+      if: always() # ensures this test always runs even if test fails
       with:
         name: docker tests
         path: ${{ runner.temp }}/test-output/*.xml
+        path-replace-backslashes: 'true'
         reporter: java-junit
-        fail-on-empty: false
+        fail-on-empty: 'false'
+        fail-on-error: 'false'
         max-annotations: 0 # This uses `git ls-files` which windows doesn't like
+
+    - name: Fail workflow if tests failed
+      if: steps.run-tests.outcome == 'failure'
+      run: exit 1
+      shell: bash -euo pipefail -c "source nix.source && exec bash -euo pipefail $0" "{0}"
